spring.application.name=Salud_CR


# Puerto de la app

server.port= 8080

# Configuracion Thymeleaf

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Configuracion recursos estaticos

spring.mvc.static-path-pattern=/static/**

# Logging

logging.level.root=INFO
logging.level.com.salud_cr=DEBUG



